### ISSUE TITLE
Make the sandbox work on vagrant

### ISSUE THREAD

**Issue by laureenas** [ManoSeimas/manoseimas.lt#71]
Checkout manoseimas.lt repo into a new sandbox and make the sandbox work using vagrant virtualization.

**Comment by mgedmin** [comment]
This needs a definition of "work".  This works today:
- [x] `vagrant up`
- [x] `vagrant ssh`
- [x] run `make` to do a build
- [x] run `make test` to run tests
- [x] run `bin/django migrate` to create DB tables
- [x] run `bin/initscrapy` to create CouchDB views
- [x] run `make run` to start django
- [x] run `bin/scrapy crawl mps` to crawl some data
- [x] run `bin/scrapy crawl stenograms` to crawl some data
- [x] run `bin/scrapy crawl law_projects` to crawl some data
- [x] run `bin/django couchdb_sync_id` to do stuff
- [x] run `bin/django syncsittings --update` (used to be broken, but I fixed it, see #59)
- [x] run `bin/django syncmps` (NB: takes 20 minutes)

This doesn't work:
- [ ] visit the site at http://localhost:8000 (bug #61)
- [ ] run `bin/scrapy crawl sittings` to crawl some data (#72)
- [ ] run `bin/django recompute_stats` to do stuff (#58)

These I haven't tried yet:
- [ ] run `bin/django syncpositions`
